### PR TITLE
add file with JupyterLab shortcuts

### PR DESCRIPTION
**Pull request by KimboGilda**
I 've made a first attempt to create a pull request, by adding a file to new branch (bako_branch). Please check if it is working @ratnanil

### CODE REVIEW

**Review by ratnanil — CHANGES_REQUESTED** [review]
Hey Nikos. Great idea! Can you include this in an appropriate .ipynb? 

PS: I'm mainly doing this to test the workflow via pull requests..

**Comment by KimboGilda** [comment]
> 
> 
> Hey Nikos. Great idea! Can you include this in an appropriate .ipynb?
> 
> PS: I'm mainly doing this to test the workflow via pull requests..

Sure, I will do so.

**Comment by ratnanil** [comment]
Merging the changes by nikos

**Comment by ratnanil** [comment]
Hi Nikos! I'm not sure where to place the shortcuts in the document, maby you can make a suggestion? Also: the shortcuts are described in English, but the document should be in german! Maybe I will find the time to propperly integrate this, but I haven't found it till now..

**Comment by KimboGilda** [comment]
> 
> 
> Hi Nikos! I'm not sure where to place the shortcuts in the document, maby you can make a suggestion? Also: the shortcuts are described in English, but the document should be in german! Maybe I will find the time to propperly integrate this, but I haven't found it till now..

Hi Nils. I will try to fix it tomorrow!

**Comment by ratnanil** [comment]
Make sure to pull the latest version!

**Pull request merged**
